// web-svelte/src/lib/components/InviteUser.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from '$lib/components/ui/card';
  import { Input } from '$lib/components/ui/input';
  import { Control, Description, Field, FieldErrors, Label } from '$lib/components/ui/form';
  import { superForm, type Infer, type SuperValidated } from 'sveltekit-superforms';
  import { inviteFormSchema } from '$lib/validation';
  import { zodClient } from 'sveltekit-superforms/adapters';

  type Props = {
    data: SuperValidated<Infer<typeof inviteFormSchema>>;
  };
  const { data }: Props = $props();

  const form = superForm(data, {
    validators: zodClient(inviteFormSchema),
  });

  const { form: formData, message, enhance } = form;
</script>

<Card class="max-w-md">
  <CardHeader>
    <CardTitle>Invite User</CardTitle>
    <CardDescription>
      New users can be configured here and invited with their email address
    </CardDescription>
  </CardHeader>
  <CardContent>
    <form method="POST" action="/auth?/invite" use:enhance>
      <Field {form} name="first_name">
        <Control let:attrs>
          <Label>
            First Name
            <Input {...attrs} bind:value={$formData.first_name} placeholder="John" />
          </Label>
        </Control>
        <Description class="sr-only">The new user's first name</Description>
        <FieldErrors />
      </Field>
      <Field {form} name="last_name">
        <Control let:attrs>
          <Label>
            Last Name
            <Input {...attrs} bind:value={$formData.last_name} placeholder="Doe" />
          </Label>
        </Control>
        <Description class="sr-only">The new user's last name</Description>
        <FieldErrors />
      </Field>
      <Field {form} name="email">
        <Control let:attrs>
          <Label>
            Email
            <Input {...attrs} bind:value={$formData.email} placeholder="johndoe@example.com" />
          </Label>
        </Control>
        <Description class="sr-only">
          The new user's email address; they will receive an invite email
        </Description>
        <FieldErrors />
      </Field>
      <Field {form} name="phone_number">
        <Control let:attrs>
          <Label>
            Phone Number
            <Input {...attrs} bind:value={$formData.phone_number} placeholder="555-555-5555" />
          </Label>
        </Control>
        <Description class="sr-only">The new user's phone number</Description>
        <FieldErrors />
      </Field>
      <Button class="mt-4 w-full" type="submit">Send Invite</Button>
      <p class="mt-4">
        Message: {$message}
      </p>
    </form>
  </CardContent>
</Card>

// web/components/InviteUser.tsx
"use client";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { invite } from "@/lib/actions/auth";
import { InviteFormSchema, inviteFormSchema } from "@/lib/validation";
import { zodResolver } from "@hookform/resolvers/zod";
import { Send } from "lucide-react";
import { useCallback } from "react";
import { useForm } from "react-hook-form";

export default function InviteUser() {
  const form = useForm<InviteFormSchema>({
    resolver: zodResolver(inviteFormSchema),
    defaultValues: {
      email: "",
      first_name: "",
      last_name: "",
      phone_number: "",
    },
  });

  const onSubmit = useCallback(
    async (values: InviteFormSchema) => {
      form.reset();
      await invite(window.location.origin, values);
    },
    [form]
  );

  return (
    <Card className="max-w-md">
      <CardHeader>
        <CardTitle>Invite User</CardTitle>
        <CardDescription>
          New users can be configured here and invited with their email address
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form
            className="flex flex-col"
            onSubmit={form.handleSubmit(onSubmit)}
          >
            <FormField
              control={form.control}
              name="first_name"
              render={({ field }) => (
                <FormItem>
                  <div className="sm:grid sm:grid-cols-form sm:items-baseline space-y-2">
                    <FormLabel className="text-bold">First Name</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="John"
                        autoComplete="none"
                        {...field}
                      />
                    </FormControl>
                  </div>
                  <FormDescription className="sr-only">
                    The new user's first name
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="last_name"
              render={({ field }) => (
                <FormItem>
                  <div className="sm:grid sm:grid-cols-form sm:items-baseline space-y-2">
                    <FormLabel className="text-bold">Last Name</FormLabel>
                    <FormControl>
                      <Input placeholder="Doe" autoComplete="none" {...field} />
                    </FormControl>
                  </div>
                  <FormDescription className="sr-only">
                    The new user's last name
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <div className="sm:grid sm:grid-cols-form sm:items-baseline space-y-2">
                    <FormLabel className="text-bold">Email</FormLabel>
                    <FormControl>
                      <Input
                        type="email"
                        placeholder="johndoe@example.com"
                        autoComplete="none"
                        {...field}
                      />
                    </FormControl>
                  </div>
                  <FormDescription className="sr-only">
                    The new user's email address
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="phone_number"
              render={({ field }) => (
                <FormItem>
                  <div className="sm:grid sm:grid-cols-form sm:items-baseline space-y-2">
                    <FormLabel className="text-bold">Phone Number</FormLabel>
                    <FormControl>
                      <Input
                        type="phone_number"
                        placeholder="123-456-7890"
                        autoComplete="none"
                        {...field}
                      />
                    </FormControl>
                  </div>
                  <FormDescription className="sr-only">
                    The new user's phone number
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button className="mt-4" type="submit">
              <Send /> Send Invite Email
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
