// web/app/dashboard/settings/change-password/page.tsx
import PageWrapper from "@/components/PageWrapper";
import ResetPassword from "@/components/ResetPassword";

export default function ChangePasswordPage() {
  return (
    <PageWrapper
      className="flex items-center justify-center"
      previousHref="/dashboard/settings"
      previousPageTitle="Settings"
    >
      <ResetPassword />
    </PageWrapper>
  );
}

// web/src/routes/(authed)/settings/change-password/+page.svelte
<script lang="ts">
  import ChangePassword from '$lib/components/ChangePassword.svelte';
  import PageWrapper from '$lib/components/PageWrapper.svelte';
  import type { PageData } from '../$types';

  type Props = {
    data: PageData;
  };
  let { data }: Props = $props();
</script>

<PageWrapper
  class="flex items-center justify-center"
  previousHref="/settings"
  previousPageTitle="Settings"
>
  <ChangePassword class="mx-auto max-w-md" form={data.form} />
</PageWrapper>
