// web/src/routes/(authed)/settings/+page.svelte
<script lang="ts">
  import LogoutButton from '$lib/components/LogoutButton.svelte';
  import { Button } from '$lib/components/ui/button';
  import { mode, resetMode } from 'mode-watcher';
  import type { PageProps } from './$types';
  import CardHeader from '$lib/components/ui/card/card-header.svelte';
  import { Card, CardContent, CardTitle } from '$lib/components/ui/card';
  import { setMode } from 'mode-watcher';
  import { LockKeyholeOpen, Moon, Settings, Settings2, Sun } from 'lucide-svelte';
  import CardDescription from '$lib/components/ui/card/card-description.svelte';
  import PageWrapper from '$lib/components/PageWrapper.svelte';
  import { Label } from '$lib/components/ui/label';
  import { Input } from '$lib/components/ui/input';

  let { data }: PageProps = $props();
</script>

{#snippet accountField(label: string, value: string)}
  <Label>
    <span class="text-bold">{label}</span>
    <Input class="mt-2" {value} readonly />
  </Label>
{/snippet}

<PageWrapper class="space-y-4 p-4">
  <h1 class="text-2xl font-semibold">Settings</h1>

  <Card class="max-w-md">
    <CardHeader>
      <CardTitle>Account Details</CardTitle>
      <CardDescription>
        These account details are only editable by members of the admin team.
      </CardDescription>
    </CardHeader>
    <CardContent class="flex flex-col gap-4">
      {@render accountField('First Name', data.profile.first_name)}
      {@render accountField('Last Name', data.profile.last_name)}
      {@render accountField('Email', data.profile.email)}
      {@render accountField('Phone Number', data.profile.phone_number)}
    </CardContent>
  </Card>
  <Button href="/dashboard/settings/change-password">
    <LockKeyholeOpen /> Change Password
  </Button>
  <Card class="max-w-md">
    <CardHeader>
      <CardTitle>Theme</CardTitle>
      <CardDescription>
        Choose your color theme. You can specify your preference between light and dark mode here,
        or you can use your device's default setting.
      </CardDescription>
    </CardHeader>
    <CardContent>
      <Button variant="secondary" class="mt-4" on:click={() => setMode('light')}>
        <Sun /> Light
      </Button>
      <Button variant="secondary" class="mt-4" on:click={() => setMode('dark')}>
        <Moon /> Dark
      </Button>
      <Button variant="secondary" class="mt-4" on:click={() => resetMode()}>
        <Settings2 />System
      </Button>
    </CardContent>
  </Card>

  <LogoutButton supabase={data.supabase} />
</PageWrapper>

// web/app/dashboard/settings/page.tsx
import PageWrapper from "@/components/PageWrapper";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getProfileById } from "@/lib/actions/queries";
import { createClient } from "@/lib/supabase/server";
import { LockKeyholeOpenIcon } from "lucide-react";
import Link from "next/link";
import { useId } from "react";

export default async function ProfilePage() {
  const supabase = await createClient();
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();
  if (!user || error) {
    throw new Error("User not found");
  }

  const profile = await getProfileById(user.id);
  console.log(profile);

  return (
    <PageWrapper
      className="space-y-4"
      previousHref="/dashboard"
      previousPageTitle="Dashboard"
    >
      <h1 className="text-4xl text-bold">Settings</h1>

      <Card className="max-w-sm">
        <CardHeader>
          <CardTitle>Account Details</CardTitle>
          <CardDescription>
            These account details are only editable by members of the admin
            team.
          </CardDescription>
        </CardHeader>
        <CardContent className="sm:grid sm:grid-cols-form sm:items-baseline space-y-2">
          <StaticField label="First Name" value={profile.first_name} />
          <StaticField label="Last Name" value={profile.last_name} />
          <StaticField label="Email" value={profile.email} />
          <StaticField label="Phone Number" value={profile.phone_number} />
        </CardContent>
      </Card>
      <Button asChild>
        <Link className="text-md" href={"/dashboard/settings/change-password"}>
          <LockKeyholeOpenIcon /> Change Password
        </Link>
      </Button>
    </PageWrapper>
  );
}

function StaticField(props: { label: string; value: string }) {
  const id = useId();

  return (
    <>
      <Label className="text-bold" htmlFor={id}>
        {props.label}
      </Label>
      <Input id={id} value={props.value} readOnly />
    </>
  );
}
