// web/app/(auth)/login/page.tsx
"use client";

import PageWrapper from "@/components/PageWrapper";
import PasswordInput from "@/components/PasswordInput";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { login } from "@/lib/actions/auth";
import { LoginFormSchema, loginFormSchema } from "@/lib/validation";
import { zodResolver } from "@hookform/resolvers/zod";
import { Turnstile } from "@marsidev/react-turnstile";
import { useCallback, useState } from "react";
import { useForm } from "react-hook-form";

export default function LoginPage() {
  const [captchaToken, setCaptchaToken] = useState<string>();
  if (!process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY) {
    throw new Error("NEXT_PUBLIC_TURNSTILE_SITE_KEY is not set");
  }

  console.log(captchaToken);

  const form = useForm<LoginFormSchema>({
    resolver: zodResolver(loginFormSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  const onSubmit = useCallback(
    (values: LoginFormSchema) =>
      captchaToken ? login(values, captchaToken) : alert("Invalid Captcha"),
    [captchaToken]
  );

  return (
    <PageWrapper className="flex items-center justify-center">
      <Card>
        <CardHeader>
          <CardTitle>Log in</CardTitle>
          <CardDescription>
            Welcome back! Use your credentials to log in
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form
              className="flex flex-col gap-2"
              onSubmit={form.handleSubmit(onSubmit)}
            >
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input type="email" placeholder="Email" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <PasswordInput placeholder="Password" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Turnstile
                siteKey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY}
                onSuccess={(token) => setCaptchaToken(token)}
              />
              <Button className="w-full mt-2 " type="submit">
                Log in
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>
    </PageWrapper>
  );
}

// web/src/routes/login/+page.svelte
<script lang="ts">
  import PageWrapper from '$lib/components/PageWrapper.svelte';
  import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
  } from '$lib/components/ui/card';
  import { Control, Description, Field, FieldErrors, Label } from '$lib/components/ui/form';
  import { Input } from '$lib/components/ui/input';
  import { loginFormSchema } from '$lib/validation';
  import { superForm } from 'sveltekit-superforms';
  import { zodClient } from 'sveltekit-superforms/adapters';
  import { Turnstile } from 'svelte-turnstile';
  import { PUBLIC_TURNSTILE_SITE_KEY } from '$env/static/public';
  import { LoaderCircle, LogIn } from 'lucide-svelte';
  import { Button } from '$lib/components/ui/button/';

  let { data } = $props();

  const form = superForm(data.form, {
    validators: zodClient(loginFormSchema),
  });

  const { form: formData, message, enhance, submitting } = form;
</script>

<h1 class="sr-only">Login Page</h1>
<PageWrapper class="flex items-center justify-center">
  <Card>
    <CardHeader>
      <CardTitle>Log in</CardTitle>
      <CardDescription>Welcome back! Use your credentials to log in</CardDescription>
    </CardHeader>
    <CardContent>
      <form method="POST">
        <Field {form} name="email">
          <Control let:attrs>
            <Label>
              <span class="sr-only">Email</span>
              <Input
                {...attrs}
                bind:value={$formData.email}
                placeholder="johndoe@example.com"
                disabled={$submitting}
              />
            </Label>
          </Control>
          <Description class="sr-only">The email address associated with your account</Description>
          <FieldErrors />
        </Field>
        <Field {form} name="password">
          <Control let:attrs>
            <Label>
              <span class="sr-only">Password</span>
              <Input
                {...attrs}
                bind:value={$formData.password}
                placeholder="super-secret-password"
                type="password"
                disabled={$submitting}
              />
            </Label>
          </Control>
          <Description class="sr-only">The password associated with your account</Description>
          <FieldErrors />
        </Field>
        <Turnstile siteKey={PUBLIC_TURNSTILE_SITE_KEY} size="flexible" />
        {#if $message}
          <p class="mt-4">
            {$message}
          </p>
        {/if}
        <Button class="mt-2 w-full" type="submit" disabled={$submitting}>
          {#if $submitting}
            <LoaderCircle class="animate-spin" /> Verifying Login...
          {:else}
            <LogIn /> Log in
          {/if}
        </Button>
      </form>
    </CardContent>
  </Card>
</PageWrapper>
