// web/components/PageWrapper.tsx
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export interface PageProps {
  className?: string;
  children: React.ReactNode;
  previousHref?: string;
  previousPageTitle?: string;
}
export default function PageWrapper(props: PageProps) {
  return (
    <main className={cn("min-h-screen h-full", props.className)}>
      {props.previousHref && (
        <Button className="absolute left-0 top-0" variant={"link"} asChild>
          <Link href={props.previousHref}>
            <ArrowLeft />
            {props.previousPageTitle
              ? `Back to ${props.previousPageTitle}`
              : "Back"}
          </Link>
        </Button>
      )}
      {props.children}
    </main>
  );
}

// web/src/lib/components/PageWrapper.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { cn } from '$lib/utils';
  import { ArrowLeft } from 'lucide-svelte';
  import type { Snippet } from 'svelte';

  type Props = {
    children: Snippet;
    class?: string;
    previousHref?: string;
    previousPageTitle?: string;
  };
  let { children, class: className, previousHref, previousPageTitle }: Props = $props();
</script>

<main class={cn('relative h-full min-h-screen', className)}>
  {#if previousHref && previousPageTitle}
    <Button class="absolute left-0 top-0" variant={'link'} href={previousHref}>
      <ArrowLeft />
      {previousPageTitle ? `Back to ${previousPageTitle}` : 'Back'}
    </Button>
  {/if}
  {@render children()}
</main>
