// web/components/PasswordInput.tsx
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Eye, EyeOff } from "lucide-react";
import { ComponentProps, useState } from "react";

export default function PasswordInput(
  props: Omit<ComponentProps<typeof Input>, "type">
) {
  const [showPassword, setShowPassword] = useState(false);

  return (
    <div className="relative">
      <Input type={showPassword ? "text" : "password"} {...props} />
      <Button
        className="absolute right-0 top-0"
        variant="ghost"
        tabIndex={-1}
        onClick={() => {
          setShowPassword((curr) => !curr);
        }}
      >
        {showPassword ? <Eye /> : <EyeOff />}
        <span className="sr-only">
          {showPassword ? "Hide Password" : "Show Password"} password
        </span>
      </Button>
    </div>
  );
}

// web/src/lib/components/PasswordInput.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Eye, EyeOff } from 'lucide-svelte';
  import type { ComponentProps } from 'svelte';

  type Props = Omit<ComponentProps<typeof Input>, 'type'>;
  let { value = $bindable(), ...props }: Props = $props();

  let showPassword = $state(false);
</script>

<div class="relative">
  <Input type={showPassword ? 'text' : 'password'} bind:value {...props} />
  <Button
    class="absolute right-0 top-0"
    variant="ghost"
    tabindex={-1}
    onclick={() => {
      showPassword = !showPassword;
    }}
  >
    {#if showPassword}
      <Eye />
    {:else}
      <EyeOff />
    {/if}
    <span class="sr-only">
      {showPassword ? 'Hide Password' : 'Show Password'} password
    </span>
  </Button>
</div>
